//-----------------------------------------------
//  Generated by Jet LiveSource (TM)
//  v2.0
//  on Thu Jun 21 17:42:17 EEST 2012
//  Author  :Michael Mountrakis mountrakis@uit.gr
//  Version :1.0.0
//  Comments:
//  Example of Live Source configuration, Enjoy....
//-----------------------------------------------



package gr.uit.jetexamples;
import java.sql.*;



public class FunCheckWeatherProc{

      private Integer pTempH;
      public Integer  getPTempH(){
      return this.pTempH;
   }
      public void  setPTempH( Integer pTempH ){
      this.pTempH = pTempH;
   }
      private Integer pTempL;
      public Integer  getPTempL(){
      return this.pTempL;
   }
      public void  setPTempL( Integer pTempL ){
      this.pTempL = pTempL;
   }
      private String returns;

      public String  getReturns(){
      return this.returns;
   }
      public void  setReturns( String returns ){
      this.returns = returns;
   }
   public FunCheckWeatherProc(){
   }

public static  FunCheckWeatherProc   callFunCheckWeather(
	Connection connection,
	String p_city, 
	java.sql.Date p_created, 
	Integer p_temp_h, 
	Integer p_temp_l
	) throws SQLException{
   String sql_cmd = "";
   CallableStatement cs = null;

   sql_cmd = "{ call ? = fun_check_weather(?,?,?,?)}";  //Callable Statement

   cs = connection.prepareCall(sql_cmd);

   cs.registerOutParameter(1,Types.VARCHAR);
   cs.setString( 2,p_city);
   cs.setDate( 3,p_created);
   cs.registerOutParameter(4,Types.INTEGER);
   cs.registerOutParameter(5,Types.INTEGER);


   cs.execute();

   FunCheckWeatherProc   results =
	 new FunCheckWeatherProc();
   results.setReturns(cs.getString(1));
   results.setPTempH(cs.getInt(4));
   results.setPTempL(cs.getInt(5));
   return results;
}

}
