//-----------------------------------------------
//  Generated by Jet LiveSource (TM)
//  v2.0
//  on Thu Jun 21 17:42:17 EEST 2012
//  Author  :Michael Mountrakis mountrakis@uit.gr
//  Version :1.0.0
//  Comments:
//  Example of Live Source configuration, Enjoy....
//-----------------------------------------------



package gr.uit.jetexamples;
import java.sql.*;



public class FunNoArgsProc{

      private Integer returns;

      public Integer  getReturns(){
      return this.returns;
   }
      public void  setReturns( Integer returns ){
      this.returns = returns;
   }
   public FunNoArgsProc(){
   }

public static  FunNoArgsProc   callFunNoArgs(
	Connection connection
	) throws SQLException{
   String sql_cmd = "";
   CallableStatement cs = null;

   sql_cmd = "{ call ? = fun_no_args()}";  //Callable Statement

   cs = connection.prepareCall(sql_cmd);

   cs.registerOutParameter(1,Types.INTEGER);


   cs.execute();

   FunNoArgsProc   results =
	 new FunNoArgsProc();
   results.setReturns(cs.getInt(1));
   return results;
}

}
