//-----------------------------------------------
//  Generated by Jet LiveSource (TM)
//  v2.0
//  on Thu Jun 21 17:42:17 EEST 2012
//  Author  :Michael Mountrakis mountrakis@uit.gr
//  Version :1.0.0
//  Comments:
//  Example of Live Source configuration, Enjoy....
//-----------------------------------------------



package gr.uit.jetexamples;
import java.util.*;
import java.sql.*;

public class Weather{



   public Weather(){
      super();
}

   private Integer id;
   private String city;
   private Integer tempLo;
   private Integer tempHi;
   private Double humidity;
   private Double press;
   private java.sql.Date created;


//  Getters
   public Integer  getId(){
      return this.id;
   }
   public String  getCity(){
      return this.city;
   }
   public Integer  getTempLo(){
      return this.tempLo;
   }
   public Integer  getTempHi(){
      return this.tempHi;
   }
   public Double  getHumidity(){
      return this.humidity;
   }
   public Double  getPress(){
      return this.press;
   }
   public java.sql.Date  getCreated(){
      return this.created;
   }


//  Setters
   public void  setId( Integer id ){
      this.id = id;
   }
   public void  setCity( String city ){
      this.city = city;
   }
   public void  setTempLo( Integer tempLo ){
      this.tempLo = tempLo;
   }
   public void  setTempHi( Integer tempHi ){
      this.tempHi = tempHi;
   }
   public void  setHumidity( Double humidity ){
      this.humidity = humidity;
   }
   public void  setPress( Double press ){
      this.press = press;
   }
   public void  setCreated( java.sql.Date created ){
      this.created = created;
   }
   public String toString(){
      String jtxt = "";
      jtxt += "id=" + this.id + " , ";
      jtxt += "city=" + this.city + " , ";
      jtxt += "tempLo=" + this.tempLo + " , ";
      jtxt += "tempHi=" + this.tempHi + " , ";
      jtxt += "humidity=" + this.humidity + " , ";
      jtxt += "press=" + this.press + " , ";
      jtxt += "created=" + this.created + " , ";
      return jtxt;
   }

}//class
